spring:
  thymeleaf:
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  # druid
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 2
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  # static
  resources:
      add-mappings: true
      # 缓存时间（s）
      cache-period: 3600
      chain.cache: true
      chain.enabled: true
      chain.gzipped: true
      chain.html-application-cache: true
      static-locations: classpath:/static/

  # rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
#        消费者数量
        concurrency: 10
        max-concurrency: 10
#        消费者每次从队列中获取的消息数量
        prefetch: 1
#        消费者自动启动
        auto-startup: true
#        消费失败，自动重新入队
        default-requeue-rejected: true
    template:
      retry:
#      启用发送重试
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0




# mybatis
mybatis:
  type-aliases-package: com.earthchen.seckill.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapperLocations: classpath:com/earthchen/seckill/dao/*.xml
  
  




  #redis
redis:
  host: 127.0.0.1
  port: 6379
  timeout: 3
  password: 123456
  poolMaxTotal: 10
  poolMaxIdle: 10
  poolMaxWait: 3







